name: CI
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
      - name: Deny scan
        run: |
          . .venv/bin/activate
          bash scripts/deny_scan.sh
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
