name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff
      - name: Lint
        run: |
          ruff check babbel tests
      - name: Grep Gate
        run: |
          set -e
          if grep -RInE '(protocols_enabled|protocolsToggled|btnProtocols|show_protocols)' -- . \
            --exclude-dir=venv --exclude-dir=.venv --exclude-dir=__pycache__ ; then
            echo "Forbidden protocol-toggle references found."
            exit 1
          fi
          echo "Grep gate passed."
      - name: Run tests
        run: |
          pytest -q
