name: Nightly Policy Scan
on:
  schedule:
    - cron: '17 4 * * *'
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deny scan
        run: bash scripts/deny_scan.sh
