[server]
headless = true
runOnSave = true
port = 8501

[theme]
base = "dark"
primaryColor = "#16a085"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#2c2c2c"
textColor = "#f0f0f0"
font = "sans serif"
